### ISSUE TITLE
Text hard to read on selected menu item

### ISSUE THREAD

**Issue by TheRedstoneRadiant** [canvasplus/extension#57]
Example occurrence:
![image](https://user-images.githubusercontent.com/76220359/234780088-5245ac15-6420-4aec-8a84-200e46cd1e32.png)

Seems like it's because of this CSS value:
![image](https://user-images.githubusercontent.com/76220359/234780151-ed4d013b-f6bc-4720-980c-e23bea0e1cc7.png)

Possible fix:
```css
.ic-app-header__menu-list-item--active > menu-item__text {
    color: var(--ic-brand-global-nav-menu-item__text-color);
}
```

Also, some menu items are inconsistently underlined:
![image](https://user-images.githubusercontent.com/76220359/234780486-d497ca42-a5b5-4846-8ade-cd23c9c19b15.png)
